scenario: server
model_path: /data/mlperf_llama2/models/Llama-2-70b-chat-hf
dataset_path: /data/mlperf_llama2/dataset/open_orca_gpt4_tokenized_llama.sampled_24576.pkl
tensor_parallel_size: 2      # both A100 80GB on node
batch_size: 8
dtype: bfloat16
total_sample_count: 24576
max_output_tokens: 1024
system_id: linux_a100_vllm
min_duration_ms: 120000
target_qps: 0.5
max_query_count: 200
