{
 "title": "Infrastructure mine",
 "time": { "from": "2026-06-03T09:36:41.387Z", "to": "2026-06-03T09:47:23.859Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ml_net_interface_bytes_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ml_training_nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ethernet — Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ml_net_interface_bytes_total{transport=\"ethernet\"}[5m])",
     "legendFormat": "{{instance}} {{interface}} {{direction}}"
    }
   ]
  },
  {
   "title": "Ethernet — Packets/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ml_net_interface_packets_total{transport=\"ethernet\"}[5m])",
     "legendFormat": "{{instance}} {{interface}} {{direction}}"
    }
   ]
  },
  {
   "title": "network interface stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, transport) (\n  ml_net_interface_bytes_total{direction=\"tx\", instance=~\"$instance.*\"}\n  -\n  last_over_time(ml_net_interface_bytes_total{direction=\"tx\", instance=~\"$instance.*\"}[$__range] @ start())\n)",
     "legendFormat": "{{instance}} {{transport}}"
    }
   ]
  },
  {
   "title": "PCIe stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ml_pcie_bandwidth_bytes_per_sec",
     "legendFormat": "{{instance}} direction: {{direction}} gpu_index: {{gpu_index}}"
    }
   ]
  }
 ]
}